# Generated by Django 5.0.2 on 2025-05-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default='No phone provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
